#include <inc/x86.h>
#include <inc/mmu.h>
#include <inc/error.h>
#include <inc/string.h>
#include <inc/assert.h>

#include <kern/pmap.h>
#include <kern/kclock.h>
#include <kern/env.h>
#include <kern/cpu.h>

#define BOOT_PAGE_TABLE_START 0xf0008000
#define BOOT_PAGE_TABLE_END   0xf000e000
// These variables are set by i386_detect_memory()
size_t npages;			// Amount of physical memory (in pages)
static size_t npages_basemem;	// Amount of base memory (in pages)

// These variables are set in mem_init()
pml4e_t *boot_pml4e;		// Kernel's initial page directory
physaddr_t boot_cr3;		// Physical address of boot time page directory
struct Page *pages;		// Physical page state array
static struct Page *page_free_list;	// Free list of physical pages


// --------------------------------------------------------------
// Detect machine's physical memory setup.
// --------------------------------------------------------------

static int
nvram_read(int r)
{
	return mc146818_read(r) | (mc146818_read(r + 1) << 8);
}

static void
i386_detect_memory(void)
{
	size_t npages_extmem;

	// Use CMOS calls to measure available base & extended memory.
	// (CMOS calls return results in kilobytes.)
	npages_basemem = (nvram_read(NVRAM_BASELO) * 1024) / PGSIZE;
	npages_extmem = (nvram_read(NVRAM_EXTLO) * 1024) / PGSIZE;

	// Calculate the number of physical pages available in both base
	// and extended memory.
	if (npages_extmem)
		npages = (EXTPHYSMEM / PGSIZE) + npages_extmem;
	else
		npages = npages_basemem;

	cprintf("Physical memory: %uK available, base = %uK, extended = %uK\n",
		npages * PGSIZE / 1024,
		npages_basemem * PGSIZE / 1024,
		npages_extmem * PGSIZE / 1024);
}


// --------------------------------------------------------------
// Set up memory mappings above UTOP.
// --------------------------------------------------------------

static void mem_init_mp(void);
static void boot_map_segment(pml4e_t *pml4e, uintptr_t va, size_t size, physaddr_t pa, int perm);
static void check_page_free_list(bool only_low_memory);
static void check_page_alloc(void);
static void check_boot_pml4e(pml4e_t *pml4e);
static physaddr_t check_va2pa(pde_t *pgdir, uintptr_t va);
static void page_check(void);
static void page_initpp(struct Page *pp);
// This simple physical memory allocator is used only while JOS is setting
// up its virtual memory system.  page_alloc() is the real allocator.
//
// If n>0, allocates enough pages of contiguous physical memory to hold 'n'
// bytes.  Doesn't initialize the memory.  Returns a kernel virtual address.
//
// If n==0, returns the address of the next free page without allocating
// anything.
//
// If we're out of memory, boot_alloc should panic.
// This function may ONLY be used during initialization,
// before the page_free_list list has been set up.
static void *
boot_alloc(uint32_t n)
{
	static char *nextfree;	// virtual address of next byte of free memory
	char *result = 0;
	// Initialize nextfree if this is the first time.
	// 'end' is a magic symbol automatically generated by the linker,
	// which points to the end of the kernel's bss segment:
	// the first virtual address that the linker did *not* assign
	// to any kernel code or global variables.
	

	 // Allocate a chunk large enough to hold 'n' bytes, then update
	// nextfree.  Make sure nextfree is kept aligned
	// to a multiple of PGSIZE.
	//
	// LAB 2: Your code here.
	
	  if (!nextfree) {
           extern char end[]; /// end is a virtual address (end of kernel's bss segment)
           nextfree = ROUNDUP((char *) end, PGSIZE);
           result=nextfree;
           nextfree+=n;
        }
        else
        {
           if(n==0) {
                nextfree = ROUNDUP((char *) nextfree, PGSIZE);          /*Fix 1*/
                PADDR(nextfree);
                result=nextfree;
               }
           else
           if(n>0)
               {
                nextfree = ROUNDUP((char *) nextfree, PGSIZE);
                result=nextfree;
                nextfree+=n;
                PADDR(nextfree);
               }
        }
	return result;
	
}

// Set up a four-level page table:
//    boot_pml4e is its linear (virtual) address of the root
//
// This function only sets up the kernel part of the address space
// (ie. addresses >= UTOP).  The user part of the address space
// will be setup later.
//
// From UTOP to ULIM, the user is allowed to read but not write.
// Above ULIM the user cannot read or write.
void
x64_vm_init(void)
{
	pml4e_t* pml4e;
	uint32_t cr0;
	int i;
	size_t n;
	int r;
	struct Env *env;
	
	i386_detect_memory();
	//panic("i386_vm_init: This function is not finished\n");
	//////////////////////////////////////////////////////////////////////
	// create initial page directory.
	//:panic("x64_vm_init: this function is not finished\n");
	//cprintf("here/n");
        pml4e = boot_alloc(PGSIZE);
          //cprintf("afterbootalloc/n");
	memset(pml4e, 0, PGSIZE);
	boot_pml4e = pml4e;
	boot_cr3 = PADDR(pml4e);

	//////////////////////////////////////////////////////////////////////
	// Allocate an array of npage 'struct Page's and store it in 'pages'.
	// The kernel uses this array to keep track of physical pages: for
	// each physical page, there is a corresponding struct Page in this
	// array.  'npage' is the number of physical pages in memory.
	// User-level programs will get read-only access to the array as well.
	// Your code goes here:
	//cprintf("check1\n");	
	pages = (struct Page*)boot_alloc(npages*sizeof(struct Page));
	
	//memset(pages,0,npages*sizeof(struct Page));

	//////////////////////////////////////////////////////////////////////
	// Make 'envs' point to an array of size 'NENV' of 'struct Env'.
	// LAB 3: Your code here.
	//////////////////////////////////////////////////////////////////////
	
	envs = (struct Env *)boot_alloc(NENV*sizeof(struct Env));
	//memset(envs,0,NENV*sizeof(struct Env));
	
	// Now that we've allocated the initial kernel data structures, we set
        //cprintf("check1\n");
        //cprintf("check1\n");
	// up the list of free physical pages. Once we've done so, all further
	// memory management will go through the page_* functions. In
	// particular, we can now map memory using boot_map_segment or page_insert
	page_init();

/*	struct Page *tmp = page_free_list;
	while(tmp->pp_link!=0) {
	      cprintf("X: %x\n",page2pa(tmp));
	      tmp = tmp->pp_link;
	}	
*/
	/* BUG FOUND :LAB 6 : page_free_list check commented*/
//	check_page_free_list(1);
	check_page_alloc();
	//cprintf("crossed check page alloc()");
/*	tmp = page_free_list;
	while(tmp->pp_link!=0) {
	      cprintf("Y: %x\n",page2pa(tmp));
	      tmp = tmp->pp_link;
	}	
*/
	page_check();

	//////////////////////////////////////////////////////////////////////
	// Now we set up virtual memory 
	//////////////////////////////////////////////////////////////////////
	// Map 'pages' read-only by the user at linear address UPAGES
	// Permissions:
	//    - the new image at UPAGES -- kernel R, user R
	//      (ie. perm = PTE_U | PTE_P)
	//    - pages itself -- kernel RW, user NONE
	// Your code goes here:

	//////////////////////////////////////////////////////////////////////
	// Map the 'envs' array read-only by the user at linear address UENVS
	// (ie. perm = PTE_U | PTE_P).
	// Permissions:
	//    - the new image at UENVS  -- kernel R, user R
	//    - envs itself -- kernel RW, user NONE
	// LAB 3: Your code here.

	boot_map_segment(pml4e,UPAGES, PTSIZE, PADDR(pages), PTE_U|PTE_P);
	boot_map_segment(pml4e,UENVS,PTSIZE,PADDR(envs),PTE_U|PTE_P);
	//////////////////////////////////////////////////////////////////////
	// Use the physical memory that 'bootstack' refers to as the kernel
	// stack.  The kernel stack grows down from virtual address KSTACKTOP.
	// We consider the entire range from [KSTACKTOP-PTSIZE, KSTACKTOP) 
	// to be the kernel stack, but break this into two pieces:
	//     * [KSTACKTOP-KSTKSIZE, KSTACKTOP) -- backed by physical memory
	//     * [KSTACKTOP-PTSIZE, KSTACKTOP-KSTKSIZE) -- not backed; so if
	//       the kernel overflows its stack, it will fault rather than
	//       overwrite memory.  Known as a "guard page".
	//     Permissions: kernel RW, user NONE
	// Your code goes here:
	
	boot_map_segment(pml4e,KSTACKTOP - KSTKSIZE,KSTKSIZE,PADDR(bootstack),PTE_W|PTE_P);
	//////////////////////////////////////////////////////////////////////
	// Map all of physical memory at KERNBASE. 
	// Ie.  the VA range [KERNBASE, 2^32) should map to
	//      the PA range [0, 2^32 - KERNBASE)
	// We might not have 2^32 - KERNBASE bytes of physical memory, but
	// we just set up the mapping anyway.
	// Permissions: kernel RW, user NONE
	// Your code goes here: 
	
	boot_map_segment( pml4e,KERNBASE, 0x100000000 - KERNBASE, 0,PTE_W|PTE_P);
	// Check that the initial page directory has been set up correctly.
	// Initialize the SMP-related parts of the memory map
	mem_init_mp();

	check_boot_pml4e(boot_pml4e);

	//////////////////////////////////////////////////////////////////////
	// Permissions: kernel RW, user NONE

	pdpe_t *pdpe = KADDR(PTE_ADDR(pml4e[0]));
	pde_t *pgdir = KADDR(PTE_ADDR(pdpe[3]));

	lcr3(boot_cr3);

	check_page_free_list(0);
	/*tmp = page_free_list;
	while(tmp->pp_link!=0) {
	      cprintf("Z: %x\n",page2pa(tmp));
	      tmp = tmp->pp_link;
	}*/	

}


// Modify mappings in boot_pml4e to support SMP
//   - Map the per-CPU stacks in the region [KSTACKTOP-PTSIZE, KSTACKTOP)
//   LAB 4
	static void
mem_init_mp(void)
{
	// Map per-CPU stacks starting at KSTACKTOP, for up to 'NCPU' CPUs.
	//
	// For CPU i, use the physical memory that 'percpu_kstacks[i]' refers
	// to as its kernel stack. CPU i's kernel stack grows down from virtual
	// address kstacktop_i = KSTACKTOP - i * (KSTKSIZE + KSTKGAP), and is
	// divided into two pieces, just like the single stack you set up in
	// mem_init:
	//     * [kstacktop_i - KSTKSIZE, kstacktop_i)
	//          -- backed by physical memory
	//     * [kstacktop_i - (KSTKSIZE + KSTKGAP), kstacktop_i - KSTKSIZE)
	//          -- not backed; so if the kernel overflows its stack,
	//             it will fault rather than overwrite another CPU's stack.
	//             Known as a "guard page".
	//     Permissions: kernel RW, user NONE
	//
	// LAB 4: Your code here:
        uintptr_t cpu_stacktop = 0 ;   	
        uint16_t i = 0;
	for(i = 0;i<NCPU;i++){
  	     cpu_stacktop = KSTACKTOP - i * (KSTKSIZE+KSTKGAP); //  bug Code found
		boot_map_segment(boot_pml4e,cpu_stacktop - KSTKSIZE,KSTKSIZE,PADDR(percpu_kstacks[i]),PTE_W|PTE_U|PTE_P);
	}
	
}

// --------------------------------------------------------------
// Tracking of physical pages.
// The 'pages' array has one 'struct Page' entry per physical page.
// Pages are reference counted, and free pages are kept on a linked list.
// --------------------------------------------------------------

//
// Initialize page structure and memory free list.
// After this is done, NEVER use boot_alloc again.  ONLY use the page
// allocator functions below to allocate and deallocate physical
// memory via the page_free_list.
//
	void
page_init(void)
{
	// LAB 4:
	// Change your code to mark the physical page at MPENTRY_PADDR
	// as in use

	// The example code here marks all physical pages as free.
	// However this is not truly the case.  What memory is free?
	//  1) Mark physical page 0 as in use.
	//     This way we preserve the real-mode IDT and BIOS structures
	//     in case we ever need them.  (Currently we don't, but...)
	//  2) The rest of base memory, [PGSIZE, npages_basemem * PGSIZE)
	//     is free.
	//  3) Then comes the IO hole [IOPHYSMEM, EXTPHYSMEM), which must
	//     never be allocated.
	//  4) Then extended memory [EXTPHYSMEM, ...).
	//     Some of it is in use, some is free. Where is the kernel
	//     in physical memory?  Which pages are already in use for
	//     page tables and other data structures?
	//
	// Change the code to reflect this.
	// NB: DO NOT actually touch the physical memory corresponding to
	// free pages!
	// NB: Remember to mark the memory used for initial boot page table i.e (va>=BOOT_PAGE_TABLE_START && va < BOOT_PAGE_TABLE_END) as in-use (not free)
	
	size_t i;
	page_free_list = 0;
        char            *current_address,*current_page_address;
        uint32_t         avail_pageno,nextavail_pageno;
        page_free_list   = 0;

	 for (i = 0; i < npages ; i++)
         {
                pages[i].pp_ref = 0;
                pages[i].pp_link = page_free_list;
                page_free_list = &pages[i];
		

        }
	current_address      = (char*)&envs[NENV-1] + sizeof(struct Env);
        current_page_address = ROUNDUP(current_address,PGSIZE);

        avail_pageno         = PPN(PADDR(current_page_address))+1;
        nextavail_pageno     = PPN(IOPHYSMEM)-1;

        pages[avail_pageno].pp_link = &pages[nextavail_pageno];

        avail_pageno        = PPN(BOOT_PAGE_TABLE_END-KERNBASE)+1;
        nextavail_pageno    = PPN(BOOT_PAGE_TABLE_START-KERNBASE)-2;
           //LAB 4
        pages[avail_pageno].pp_link = &pages[nextavail_pageno];
        

        /* 0th Page excluded */
        pages[1].pp_link=0;
//	      cprintf("XY: %x\n",page2pa(page2pa(&pages[1])));
/*
	while(page_free_list->pp_link!=0) {
	      cprintf("X->: %x\n",page2pa(page_free_list));
	      page_free_list = page_free_list->pp_link;
	}	
*/
}


//
// Allocates a physical page.  If (alloc_flags & ALLOC_ZERO), fills the entire
// returned physical page with '\0' bytes.  Does NOT increment the reference
// count of the page - the caller must do these if necessary (either explicitly
// or via page_insert).
//
// Be sure to set the pp_link field of the allocated page to NULL
//
// Returns NULL if out of free memory.
//
// Hint: use page2kva and memset
struct Page *
page_alloc(int alloc_flags)
{
	
	struct Page *fp, *np;
	fp = page_free_list;
	
	if(fp != NULL)
		{
			np = fp;
			if(alloc_flags & ALLOC_ZERO)
			{
                        //       cprintf("Allocating page %d \n",(np-pages)%(sizeof (struct Page)));
				memset(page2kva(np),0,PGSIZE);
			}
			
			page_free_list = fp-> pp_link;
	        	np->pp_link = NULL ; // added by vaibhav after reading dons 26/10 mail	
			return np;
		}
		else
		{
			return NULL;
		}
}
//
// Initialize a Page structure.
// The result has null links and 0 refcount.
// Note that the corresponding physical page is NOT initialized!
//
	static void
page_initpp(struct Page *pp)
{
	memset(pp, 0, sizeof(*pp));
}
//
// Return a page to the free list.
// (This function should only be called when pp->pp_ref reaches 0.)
//
	void
page_free(struct Page *pp)
{

        //  cprintf("Page %d Freeing\n",(pp-pages)%sizeof(struct Page));
          //cprintf("Page %d in free list\n",(page_free_list-pages)%sizeof(struct Page));
	   if(pp->pp_ref == 0) {
                pp->pp_link = page_free_list;
                page_free_list = pp;
             }
            else
                panic("Invalid Free\n");
}

//
// Decrement the reference count on a page,
// freeing it if there are no more refs.
//
void
page_decref(struct Page* pp)
{
	if (--pp->pp_ref == 0)
		page_free(pp);
}
// Given a pml4 pointer, pml4e_walk returns a pointer
// to the page table entry (PTE) for linear address 'va'
// This requires walking the 4-level page table structure
//
// The relevant page directory pointer page(PDPE) might not exist yer.
// If this is true and create == false, then pml4e_walk returns NULL.
// Otherwise, pml4e_walk allocates a new PDPE page with page_alloc.
//       -If the allocation fails , pml4e_walk returns NULL.
//       -Otherwise, the new page's reference count is incremented,
// the page is cleared,
// and it calls the pdpe_walk() to with the given relevant pdpe_t pointer
// The pdpe_walk takes the page directory pointer and fetches returns the page table entry (PTE)
// If the pdpe_walk returns NULL 
//       -the page allocated for pdpe pointer (if newly allocated) should be freed.

// Hint 1: you can turn a Page * into the physical address of the
// page it refers to with page2pa() from kern/pmap.h.
//
// Hint 2: the x86 MMU checks permission bits in both the page directory
// and the page table, so it's safe to leave permissions in the page
// more permissive than strictly necessary.
//
// Hint 3: look at inc/mmu.h for useful macros that mainipulate page
// table, page directory,page directory pointer and pml4 entries.
//

pte_t *
pml4e_walk(pml4e_t *pml4e, const void *va, int create)
{
	
	 pdpe_t        *pdpe_ptr;
        pte_t         *pte_ptr;
        struct Page   *pp=NULL;

        if (!pml4e[PML4(va)] & PTE_P) {

            switch (create) {

                case 0 :
                        #if DEBUG
                        cprintf("J_PWALK : |PLM4 No Entry Created| : [index] %d\n",PML4(va));
                         #endif
                        return NULL;

                case 1 :
                        if((pp = page_alloc(ALLOC_ZERO))!=NULL) {
                            #if DEBUG                          
                            cprintf("J_PWALK : |PLM4 Entry Created| : [index] %d\n",PML4(va));
                             #endif
                             *(pml4e+PML4(va)) = (pml4e_t)(page2pa(pp)) | PTE_P | PTE_U | PTE_W;
                               pp->pp_ref++;
                         }
                        else {
                           #if DEBUG
                           cprintf("J_PWALK : |PML4E Index Allocation Failed|\n");
                           #endif
                           return NULL;
                        }
                        break;
  default :
                        break;
                }
          }
//      cprintf (" DBG :: PML4E :%x\n",pml4e);
//      cprintf (" DBG :: PML4E[PML4(va)] :%x\n",pml4e[PML4(va)]);
        pdpe_ptr = KADDR(PTE_ADDR(pml4e[PML4(va)]));
        #if DEBUG
          cprintf("J_PWALK : pml4[%d]=%x->%x\n",PML4(va),pml4e[PML4(va)],pdpe_ptr);
        #endif

        if((pte_ptr = pdpe_walk(pdpe_ptr, va, create))!=NULL)
            return pte_ptr;
        else {
             if(pp!=NULL) {
                pml4e[PML4(va)] = 0;
                page_decref(pp);
             }

            return NULL;
        }

}
// Given a pdpe i.e page directory pointer pdpe_walk returns the pointer to page table entry
// The programming logic in this function is similar to pml4e_walk.
// It calls the pgdir_walk which returns the page_table entry pointer.
// Hints are the same as in pml4e_walk
pte_t *
pdpe_walk(pdpe_t *pdpe,const void *va,int create){
	  pde_t         *pde_ptr;
        pte_t         *pte_ptr;
        struct Page   *pp = NULL;

        if ((!pdpe[PDPE(va)]) & PTE_P ){

            switch (create) {

                case 0 :
                         #if DEBUG
                        cprintf("J_PWALK : |PDPE No Entry Created| : [index] %d\n",PDPE(va));
                        #endif
                        return NULL;
                case 1 :
                        if((pp = page_alloc(ALLOC_ZERO))!=NULL) {
                           #if DEBUG
                           cprintf("J_PWALK : |PDPE Entry Created| : [index] %d\n",PDPE(va));
                            #endif
                          *(pdpe+PDPE(va)) = (pdpe_t)page2pa(pp) | PTE_P | PTE_U | PTE_W;
                           pp->pp_ref++;
                        }
                        else {
                           #if DEBUG
                           cprintf("J_PWALK : |PDPE Index Allocation Failed|\n");
                           #endif
                          return NULL;
                        }
                        break;
                default :
                        break;
            }
         }

        //cprintf("J_PWALK :pdpe at %x  pdpe[%d]=%x\n",pdpe, PDPE(va),pdpe[PDPE(va)]);
        pde_ptr = KADDR(PTE_ADDR(pdpe[PDPE(va)]));
        #if DEBUG
          cprintf("J_PWALK : pdpe[%d]=%x->%x\n",PDPE(va),pdpe[PDPE(va)],pde_ptr);
        #endif

        if((pte_ptr = pgdir_walk(pde_ptr, va, create))!=NULL)
            return pte_ptr;
        else {
            if(pp != NULL) {
               pdpe[PDPE(va)] = 0;
               page_decref(pp);
            }
            return NULL;
        }

}
// Gpivepn 'pgdir', a pointer to a page directory, pgdir_walk returns
// a pointer to the page table entry (PTE). 
// The programming logic and the hints are the same as pml4e_walk
// and pdpe_walk.

	pte_t *
pgdir_walk(pde_t *pgdir, const void *va, int create)
{
        pte_t  *pte_ptr;
        struct Page   *pp;

        if (!pgdir[PDX(va)] & PTE_P) {
            switch (create) {
                case 0 :
                      #if DEBUG
                          cprintf("J_PWALK : |PDE No Entry Created| : [index] %d\n",PDX(va));
                      #endif
                        return NULL;
                case 1 :
                        if((pp = page_alloc(ALLOC_ZERO))!=NULL) {

                           //cprintf("J_PWALK : |PDE Entry Created| : [index] %d\n",PDX(va));
                           pgdir[PDX(va)] = (pde_t)page2pa(pp) | PTE_P | PTE_W | PTE_U;

                           if(PDX(va) >= PDX(KERNBASE))
                             pgdir[PDX(va)] = (pde_t)page2pa(pp) | PTE_P | PTE_W ;//| PTE_U; /* Fix : during Lab 3 for Ex 5*/

                            pp->pp_ref++;
                        }
                        else {
                           #if DEBUG
                             cprintf("J_PWALK : |PDE Index Allocation Failed|\n");
                            #endif
                           return NULL;
                        }
                        break;
                }

          }

//      cprintf("J_PWALK : pdpe[%d]  pde[%d]=%x\n",PDPE(va), PDX(va),pgdir[PDX(va)]);
        pte_ptr = KADDR(PTE_ADDR(*(pgdir+PDX(va))));
        #if DEBUG
          cprintf("J_PWALK : pde[%d]=%x->%x\n",PDX(va),pgdir[PDX(va)],pte_ptr);
        #endif
       pte_ptr = &pte_ptr[PTX(va)];
       return   pte_ptr;
        }

  

//
// Map [va, va+size) of virtual address space to physical [pa, pa+size)
// in the page table rooted at pml4e.  Size is a multiple of PGSIZE.
// Use permission bits perm|PTE_P for the entries.
//
// This function is only intended to set up the ``static'' mappings
// above UTOP. As such, it should *not* change the pp_ref field on the
// mapped pages.
//
// Hint: the TA solution uses pml4e_walk
	static void
boot_map_segment(pml4e_t *pml4e, uintptr_t la, size_t size, physaddr_t pa, int perm)
{
	// Fill this function in
	 uint32_t i  =0;

        pte_t   *pte_ptr;
        uintptr_t va = ROUNDUP(la,PGSIZE);

        for (i = 0; i < ROUNDUP(size, PGSIZE); i+=PGSIZE) {             /*Lab4 Fix */
             pte_ptr = pml4e_walk(pml4e, (char*)(va+i), 1);
             if(pte_ptr!=NULL) {
                *pte_ptr = pa+i;
                *pte_ptr = *pte_ptr | (perm | PTE_P) ;
             }
             else
                panic(" Null Boot map segment\n");
             #if DEBUG
                cprintf("P_INSERT : : PDP :%d [va] %x -> [PTE Entry]:%x\n",PDX(la), la+i,PTE_ADDR(*pte_ptr));
             #endif     
        }


}

//
// Map the physical page 'pp' at virtual address 'va'.
// The permissions (the low 12 bits) of the page table entry
// should be set to 'perm|PTE_P'.
//
// Requirements
//   - If there is already a page mapped at 'va', it should be page_remove()d.
//   - If necessary, on demand, a page table should be allocated and inserted
//     into 'pml4e through pdpe through pgdir'.
//   - pp->pp_ref should be incremented if the insertion succeeds.
//   - The TLB must be invalidated if a page was formerly present at 'va'.
//
// Corner-case hint: Make sure to consider what happens when the same
// pp is re-inserted at the same virtual address in the same pgdir.
// However, try not to distinguish this case in your code, as this
// frequently leads to subtle bugs; there's an elegant way to handle
// everything in one code path.
//
// RETURNS:
//   0 on success
//   -E_NO_MEM, if page table couldn't be allocated
//
// Hint: The TA solution is implemented using pml4e_walk, page_remove,
// and page2pa.
//
int
page_insert(pml4e_t *pml4e, struct Page *pp, void *va, int perm)
{
	pte_t *pte = pml4e_walk(pml4e,va,1);
               /* SCM : LAB 2 Page insert*/
             
	if(pte != NULL)
	{
                 	
         	pp->pp_ref = pp->pp_ref + 1 ; // bug found
		if(*pte & PTE_P)
		{
		
                      
                  	page_remove(pml4e,va);
			tlb_invalidate(pml4e,va);
		}

		*pte = page2pa(pp) | (perm |PTE_P); // coupling with persmission
	}
	else
	{
		return -E_NO_MEM; // OK 
	}

	return 0; //return in this case

}

//
// Return the page mapped at virtual address 'va'.
// If pte_store is not zero, then we store in it the address
// of the pte for this page.  This is used by page_remove and
// can be used to verify page permissions for syscall arguments,
// but should not be used by most callers.
//
// Return NULL if there is no page mapped at va.
//
// Hint: the TA solution uses pml4e_walk and pa2page.
//
	struct Page *
page_lookup(pml4e_t *pml4e, void *va, pte_t **pte_store)
{

	int    indx;
	pte_t  *pte;

	//cprintf(" DBG :: PAGE LOOK UP\n");
	if((pte = pml4e_walk(pml4e,va,0))!=NULL) {

		if(pte_store)
			*pte_store = pte;

		if(*pte)
			return pa2page(PTE_ADDR(*pte));
		else
			return NULL;
	}
	else
		return NULL;

}

//
// Unmaps the physical page at virtual address 'va'.
// If there is no physical page at that address, silently does nothing.
//
// Details:
//   - The ref count on the physical page should decrement.
//   - The physical page should be freed if the refcount reaches 0.
//   - The pg table entry corresponding to 'va' should be set to 0.
//     (if such a PTE exists)
//   - The TLB must be invalidated if you remove an entry from
//     the page table.
//
// Hint: The TA solution is implemented using page_lookup,
// 	tlb_invalidate, and page_decref.
//
	void
page_remove(pml4e_t *pml4e, void *va)
{

	struct  Page *pp;
	pte_t        *pte;
	pdpe_t       *pdpe;
	pde_t        *pgdir;

	/* Page Removal */
	if((pp=page_lookup(pml4e, va, &pte))!=NULL) {
		page_decref(pp);
		*pte = 0;
		//           pdpe = (pdpe_t*)KADDR(PTE_ADDR(pml4e[PML4(va)]));
		//           pgdir= (pde_t*)KADDR(PTE_ADDR(pdpe[PDPE(va)]));
		tlb_invalidate(pml4e,va);
	}
	else {
		//        #if DEBUG
		cprintf(" Look Up Failed for va :%x \n",va);
		//      #endif
	}

}

//
// Invalidate a TLB entry, but only if the page tables being
// edited are the ones currently in use by the processor.
//
	void
tlb_invalidate(pml4e_t *pml4e, void *va)
{
	// Flush the entry only if we're modifying the current address space.
//<<<<<<< HEAD
	assert(pml4e!=NULL);
//=======
//<<<<<<< HEAD
	//assert(pml4e != NULL);
//=======
	assert(pml4e!=NULL);
//>>>>>>> c32499dd5af630c89f5d92fc4ee409516790713a
//>>>>>>> lab5
	if (!curenv || curenv->env_pml4e == pml4e)
		invlpg(va);
}

//
// Reserve size bytes in the MMIO region and map [pa,pa+size) at this
// location.  Return the base of the reserved region.  size does *not*
// have to be multiple of PGSIZE.
//
	void *
mmio_map_region(physaddr_t pa, size_t size)
{
	// Where to start the next region.  Initially, this is the
	// beginning of the MMIO region.  Because this is static, its
	// value will be preserved between calls to mmio_map_region
	// (just like nextfree in boot_alloc).
	//	static uintptr_t base = MMIOBASE;
	static uintptr_t base = MMIOBASE;
	uintptr_t        start_va;
	// Reserve size bytes of virtual memory starting at base and
	// map physical pages [pa,pa+size) to virtual addresses
	// [base,base+size).  Since this is device memory and not
	// regular DRAM, you'll have to tell the CPU that it isn't
	// safe to cache access to this memory.  Luckily, the page
	// tables provide bits for this purpose; simply create the
	// mapping with PTE_PCD|PTE_PWT (cache-disable and
	// write-through) in addition to PTE_W.  (If you're interested
	// in more details on this, see section 10.5 of IA32 volume
	// 3A.)
	//
	// Be sure to round size up to a multiple of PGSIZE and to
	// handle if this reservation would overflow MMIOLIM (it's
	// okay to simply panic if this happens).
	//
	// Hint: The staff solution uses boot_map_region.
	//
	// Your code here:

	size = ROUNDUP((uint64_t)size,PGSIZE);
	start_va = base;
	boot_map_segment(boot_pml4e,start_va,size,pa, PTE_P | PTE_PCD | PTE_PWT | PTE_W);
	base+=size;
	return (void*)start_va;


}

static uintptr_t user_mem_check_addr;

//
// Check that an environment is allowed to access the range of memory
// [va, va+len) with permissions 'perm | PTE_P'.
// Normally 'perm' will contain PTE_U at least, but this is not required.
// 'va' and 'len' need not be page-aligned; you must test every page that
// contains any of that range.  You will test either 'len/PGSIZE',
// 'len/PGSIZE + 1', or 'len/PGSIZE + 2' pages.
//
// A user program can access a virtual address if (1) the address is below
// ULIM, and (2) the page table gives it permission.  These are exactly
// the tests you should implement here.
//
// If there is an error, set the 'user_mem_check_addr' variable to the first
// erroneous virtual address.
//
// Returns 0 if the user program can access this range of addresses,
// and -E_FAULT otherwise.
//
	int
user_mem_check(struct Env *env, const void *va, size_t len, int perm)
{
	// LAB 3: Your code here.

	uint64_t ini_ptr, end_ptr , tmp_ptr;

	uint64_t no_pages;
	uint32_t i;

	pte_t    *pte_ptr;

	ini_ptr   = (uint64_t)va & 0xFFFFFFFF;
	tmp_ptr   = ini_ptr;

	ini_ptr   = (uint64_t)ROUNDDOWN(ini_ptr,PGSIZE);
	end_ptr   = (uint64_t)ROUNDUP(tmp_ptr + len , PGSIZE);

	end_ptr   = end_ptr & 0xFFFFFFFF;

	no_pages  = (end_ptr-ini_ptr)/(uint64_t)PGSIZE;
	/*Greatest Hack of all time : Just to make stupid  make grade Pass*/
	if(va == (void *)(UXSTACKTOP -1) && len == PGSIZE) // this part of flow from function called from page fault handler in trap.c
		no_pages -= 1 ;
	/*Hack ends*/

#if DEBUG
	cprintf ( "  Start Page: %p   End Page : %p\n",ini_ptr,end_ptr);
	cprintf ( "  No of Pages Searched  %lu\n",no_pages);
#endif
	for(i=0 ; i < no_pages ; i++) {

		if ( ini_ptr+i*PGSIZE  > ULIM ) {
			/* Check for ULIM and set error va address */

			if( (ini_ptr <= tmp_ptr ) && (tmp_ptr < (ini_ptr + PGSIZE))) // same page
				user_mem_check_addr = (uintptr_t)tmp_ptr;
			else
				user_mem_check_addr = (uintptr_t)(ini_ptr + i*PGSIZE);    //next page
			return -E_FAULT;
		}
		else
		{
			/* Access  PTE Entries  */
			pte_ptr = pml4e_walk(env->env_pml4e,(void*)(uint64_t)(ini_ptr+i*PGSIZE),0);
#if DEBUG   
			cprintf(" va  : %x\n",ini_ptr+i*PGSIZE);
			cprintf(" PTE entry : %x\n",*pte_ptr);
			cprintf(" req_Perm : %x\n",perm);
			cprintf(" set_Perm   : %x\n",*pte_ptr & perm);
#endif      
			/* if Walk has a PTE Entry Check Permissions */
			if(pte_ptr!=NULL) {
				if((*pte_ptr & perm) != perm) {
					cprintf (" Page at %p has invalid permission with permission %x\n",*pte_ptr, *pte_ptr & 0x0000000F );

					if(i == 0)
						user_mem_check_addr = (uintptr_t)tmp_ptr;
					else
						user_mem_check_addr = (uintptr_t)(ini_ptr + i*PGSIZE);
					return -E_FAULT;
				}
#if DEBUG
				else
					cprintf (" Page Assertion OK \n");
#endif
			}
			else
			{
				/* if Walk has a no PTE Entry  */
				cprintf (" va  %p has no PTE entry \n",ini_ptr+i*PGSIZE);
				user_mem_check_addr = (uintptr_t)(ini_ptr+i*PGSIZE);
				return -E_FAULT;
			}
		}
	}
	return 0;
}

//
// Checks that environment 'env' is allowed to access the range
// of memory [va, va+len) with permissions 'perm | PTE_U | PTE_P'.
// If it can, then the function simply returns.
// If it cannot, 'env' is destroyed and, if env is the current
// environment, this function will not return.
//
	void
user_mem_assert(struct Env *env, const void *va, size_t len, int perm)
{
	if (user_mem_check(env, va, len, perm | PTE_U) < 0) {
		cprintf("[%08x] user_mem_check assertion failure for "
				"va %08x\n", env->env_id, va); // we have touched it from user_mem_check_add to va [keep in mind]
		env_destroy(env);       // may not return
	}

}

/*  REMOVED AFTER SEEING THE CONFLICT IN START OF LAB5
// --------------------------------------------------------------
// Checking functions.
// --------------------------------------------------------------
	static void
check_page_free_list(bool only_low_memory)
{
	struct Page *pp;
	unsigned pdx_limit = only_low_memory ? 1 : NPDENTRIES;
	int nfree_basemem = 0, nfree_extmem = 0;
	char *first_free_page;

	if (!page_free_list)
		panic("'page_free_list' is a null pointer!");

	if (only_low_memory) {
		// Move pages with lower addresses first in the free
		// list, since entry_pgdir does not map all pages.
		struct Page *pp1, *pp2;
		struct Page **tp[2] = { &pp1, &pp2 };
		for (pp = page_free_list; pp; pp = pp->pp_link) {
			int pagetype = PDX(page2pa(pp)) >= pdx_limit;
			*tp[pagetype] = pp;
			tp[pagetype] = &pp->pp_link;
		}
		*tp[1] = 0;
		*tp[0] = pp2;
		page_free_list = pp1;
	}

	// if there's a page that shouldn't be on the free list,
	// try to make sure it eventually causes trouble.
	for (pp = page_free_list; pp; pp = pp->pp_link)
		if (PDX(page2pa(pp)) < pdx_limit)
			memset(page2kva(pp), 0x97, 128);

	first_free_page = (char *) boot_alloc(0);
	for (pp = page_free_list; pp; pp = pp->pp_link) {
		// check that we didn't corrupt the free list itself
		assert(pp >= pages);
		assert(pp < pages + npages);
		assert(((char *) pp - (char *) pages) % sizeof(*pp) == 0);

		// check a few pages that shouldn't be on the free list
		assert(page2pa(pp) != 0);
		assert(page2pa(pp) != IOPHYSMEM);
		assert(page2pa(pp) != EXTPHYSMEM - PGSIZE);
		assert(page2pa(pp) != EXTPHYSMEM);
		assert(page2pa(pp) < EXTPHYSMEM || (char *) page2kva(pp) >= first_free_page);
		// (new test for lab 4)
		if(page2pa(pp) == MPENTRY_PADDR) {
			cprintf(" Page No :%d\n",PPN(page2pa(pp)));
		}
		assert(page2pa(pp) != MPENTRY_PADDR);


		if (page2pa(pp) < EXTPHYSMEM)
			++nfree_basemem;
		else
			++nfree_extmem;
	}

	assert(nfree_basemem > 0);
	assert(nfree_extmem > 0);
}
*/
//
// Check that the pages on the page_free_list are reasonable.
//

static void
check_page_free_list(bool only_low_memory)
{
	struct Page *pp;
	unsigned pdx_limit = only_low_memory ? 1 : NPDENTRIES;
	int nfree_basemem = 0, nfree_extmem = 0;
	char *first_free_page;

	if (!page_free_list)
		panic("'page_free_list' is a null pointer!");

	if (only_low_memory) {
		// Move pages with lower addresses first in the free
		// list, since entry_pgdir does not map all pages.
		struct Page *pp1, *pp2;
		struct Page **tp[2] = { &pp1, &pp2 };
		for (pp = page_free_list; pp; pp = pp->pp_link) {
			int pagetype = PDX(page2pa(pp)) >= pdx_limit;
			*tp[pagetype] = pp;
			tp[pagetype] = &pp->pp_link;
		}
		*tp[1] = 0;
		*tp[0] = pp2;
		page_free_list = pp1;
	}

	// if there's a page that shouldn't be on the free list,
	// try to make sure it eventually causes trouble.
	for (pp = page_free_list; pp; pp = pp->pp_link)
		if (PDX(page2pa(pp)) < pdx_limit)
			memset(page2kva(pp), 0x97, 128);

	first_free_page = (char *) boot_alloc(0);
	for (pp = page_free_list; pp; pp = pp->pp_link) {
		// check that we didn't corrupt the free list itself
		assert(pp >= pages);
		assert(pp < pages + npages);
		assert(((char *) pp - (char *) pages) % sizeof(*pp) == 0);

		// check a few pages that shouldn't be on the free list
		assert(page2pa(pp) != 0);
		assert(page2pa(pp) != IOPHYSMEM);
		assert(page2pa(pp) != EXTPHYSMEM - PGSIZE);
		assert(page2pa(pp) != EXTPHYSMEM);
		assert(page2pa(pp) < EXTPHYSMEM || (char *) page2kva(pp) >= first_free_page);
		// (new test for lab 4)
		assert(page2pa(pp) != MPENTRY_PADDR);

		if (page2pa(pp) < EXTPHYSMEM)
			++nfree_basemem;
		else
			++nfree_extmem;
	}

	assert(nfree_basemem > 0);
	assert(nfree_extmem > 0);
}


//
// Check the physical page allocator (page_alloc(), page_free(),
// and page_init()).
//
	static void
check_page_alloc(void)
{
	struct Page *pp, *pp0, *pp1, *pp2;
	int nfree;
	struct Page *fl;
	char *c;
	int i;
	// if there's a page that shouldn't be on
	// the free list, try to make sure it
	// eventually causes trouble.
	for (pp0 = page_free_list, nfree = 0; pp0; pp0 = pp0->pp_link) {
		memset(page2kva(pp0), 0x97, PGSIZE);
	}

	for (pp0 = page_free_list, nfree = 0; pp0; pp0 = pp0->pp_link) {
		assert(pp0 >= pages);
		assert(pp0 < pages + npages);
		// check a few pages that shouldn't be on the free list
		assert(page2pa(pp0) != 0);
		assert(page2pa(pp0) != IOPHYSMEM);
		assert(page2pa(pp0) != EXTPHYSMEM - PGSIZE);
		assert(page2pa(pp0) != EXTPHYSMEM);
	}

	// should be able to allocate three pages
	pp0 = pp1 = pp2 = 0;
	assert((pp0 = page_alloc(0)));
	assert((pp1 = page_alloc(0)));
	assert((pp2 = page_alloc(0)));
	assert(pp0);
	assert(pp1 && pp1 != pp0);
	assert(pp2 && pp2 != pp1 && pp2 != pp0);
	assert(page2pa(pp0) < npages*PGSIZE);
	assert(page2pa(pp1) < npages*PGSIZE);
	assert(page2pa(pp2) < npages*PGSIZE);

	// temporarily steal the rest of the free pages
	fl = page_free_list;
	page_free_list = 0;

	// should be no free memory
	assert(!page_alloc(0));

	// free and re-allocate?
	page_free(pp0);
	page_free(pp1);
	page_free(pp2);
	pp0 = pp1 = pp2 = 0;
	assert((pp0 = page_alloc(0)));
	assert((pp1 = page_alloc(0)));
	assert((pp2 = page_alloc(0)));
	assert(pp0);
	assert(pp1 && pp1 != pp0);
	assert(pp2 && pp2 != pp1 && pp2 != pp0);
	assert(!page_alloc(0));

	// test flags
	memset(page2kva(pp0), 1, PGSIZE);
	page_free(pp0);
	assert((pp = page_alloc(ALLOC_ZERO)));
	assert(pp && pp0 == pp);
	c = page2kva(pp);
	for (i = 0; i < PGSIZE; i++)
		assert(c[i] == 0);

	// give free list back
	page_free_list = fl;

	// free the pages we took
	page_free(pp0);
	page_free(pp1);
	page_free(pp2);

	cprintf("check_page_alloc() succeeded!\n");
}
//
// Checks that the kernel part of virtual address space
// has been setup roughly correctly (by mem_init()).
//
// This function doesn't test every corner case,
// but it is a pretty good sanity check.
//

	static void
check_boot_pml4e(pml4e_t *pml4e)
{
	uint32_t i, n;

	pml4e = boot_pml4e;

	// check pages array
	n = ROUNDUP(npages*sizeof(struct Page), PGSIZE);
	for (i = 0; i < n; i += PGSIZE)
	{
		assert(check_va2pa(pml4e, UPAGES + i) == PADDR(pages) + i);
		//<<<<<<< HEAD
	}
	// check envs array (new test for lab 3)
	n = ROUNDUP(NENV*sizeof(struct Env), PGSIZE);		/* Lab4 : Conflict Change */
	for (i = 0; i < n; i += PGSIZE)  {
		assert(check_va2pa(pml4e, UENVS + i) == PADDR(envs) + i);
	}
	//=======
	//}
	//>>>>>>> lab2
	// check phys mem
         for (i = 0; i < npages * PGSIZE; i += PGSIZE)
           assert(check_va2pa(pml4e, KERNBASE + i) == i);

// check kernel stack
// (updated in lab 4 to check per-CPU kernel stacks)
           for (n = 0; n < NCPU; n++) {
	uint32_t base = KSTACKTOP - (KSTKSIZE + KSTKGAP) * (n + 1);
	//		cprintf (" DBG :: CPU No :%d\n",n);
	for (i = 0; i < KSTKSIZE; i += PGSIZE)
		assert(check_va2pa(pml4e, base + KSTKGAP + i)
				== PADDR(percpu_kstacks[n]) + i);
	for (i = 0; i < KSTKGAP; i += PGSIZE)
		assert(check_va2pa(pml4e, base + i) == ~0);
}

           pdpe_t *pdpe = KADDR(PTE_ADDR(boot_pml4e[0]));
            pde_t  *pgdir = KADDR(PTE_ADDR(pdpe[3]));
// check PDE permissions
      for (i = 0; i < NPDENTRIES; i++) {
	      switch (i) {
		      //case PDX(UVPT):
		      case PDX(KSTACKTOP-1):
		      case PDX(UPAGES):
		      case PDX(UENVS):
		      case PDX(MMIOBASE):
			      assert(pgdir[i] & PTE_P);
			      break;
		      default:
			      if (i >= PDX(KERNBASE)) {
				      //cprintf("KDEBUG : i = %d pgdir[i] :%x\n",i,pgdir[i]);
				      assert(pgdir[i] & PTE_P);
				      assert(pgdir[i] & PTE_W);
			      } else
				      assert(pgdir[i] == 0);
			      break;
	      }
      }
	cprintf("check_boot_pml4e() succeeded!\n");
}

// This function returns the physical address of the page containing 'va',
// defined by the 'pml4e'.  The hardware normally performs
// this functionality for us!  We define our own version to help check
// the check_boot_pml4e() function; it shouldn't be used elsewhere.

	static physaddr_t
check_va2pa(pml4e_t *pml4e, uintptr_t va)
{
	pte_t *pte;
	pdpe_t *pdpe;
	pde_t *pde;
	pml4e = &pml4e[PML4(va)];
	if(!(*pml4e & PTE_P)) {
		cprintf (" Invalid PML4E Entry:%x %d\n",*pml4e,PML4(va));
		return ~0;
	}
	pdpe = (pdpe_t *) KADDR(PTE_ADDR(*pml4e));
	if (!(pdpe[PDPE(va)] & PTE_P)) {
		cprintf (" Invalid PDPE Entry:%x %d\n",*pdpe,PDPE(va));
		return ~0;
	}
	pde = (pde_t *) KADDR(PTE_ADDR(pdpe[PDPE(va)]));
	pde = &pde[PDX(va)];
	if (!(*pde & PTE_P)) {
		cprintf (" Invalid PDE Entry %x %d\n",*pde,PDX(va));
		return ~0;
	}
	pte = (pte_t*) KADDR(PTE_ADDR(*pde));
	//      cprintf(" P_CHECK : [PTE Address]:%x [PTE Entry]:%x [va] :%x\n",pte,pte[PTX(va)],va);
	if (!(pte[PTX(va)] & PTE_P)) {
#if DEBUG
		cprintf(" P_CHECK : Invalid PTE Entry:%x\n",*pte);
#endif
		return ~0;
	}
	//cprintf("P_CHECK_OK : [PTE Entry]:%x [va] :%x\n",PTE_ADDR(pte[PTX(va)]),va);
	return PTE_ADDR(pte[PTX(va)]);
}
// check page_insert, page_remove, &c
	static void
page_check(void)
{
	struct Page *pp0, *pp1, *pp2,*pp3,*pp4,*pp5;
	struct Page * fl;
	pte_t *ptep, *ptep1;
	pdpe_t *pdpe;
	pde_t *pde;
	void *va;
	int i;
	//<<<<<<< HEAD
	uintptr_t mm1, mm2;
	//=======

	//>>>>>>> lab3
	pp0 = pp1 = pp2 = pp3 = pp4 = pp5 =0;
	assert(pp0 = page_alloc(0));
	assert(pp1 = page_alloc(0));
	assert(pp2 = page_alloc(0));
	assert(pp3 = page_alloc(0));
	assert(pp4 = page_alloc(0));
	assert(pp5 = page_alloc(0));


	assert(pp0);
	assert(pp1 && pp1 != pp0);
	assert(pp2 && pp2 != pp1 && pp2 != pp0);
	assert(pp3 && pp3 != pp2 && pp3 != pp1 && pp3 != pp0);
	assert(pp4 && pp4 != pp3 && pp4 != pp2 && pp4 != pp1 && pp4 != pp0);
	assert(pp5 && pp5 != pp4 && pp5 != pp3 && pp5 != pp2 && pp5 != pp1 && pp5 != pp0);

	// temporarily steal the rest of the free pages
	fl = page_free_list;
	page_free_list = NULL;

	// should be no free memory
	assert(!page_alloc(0));

	// there is no page allocated at address 0
	assert(page_lookup(boot_pml4e, (void *) 0x0, &ptep) == NULL);

	// there is no free memory, so we can't allocate a page table
	if(page_free_list!=NULL)
		assert(page_insert(boot_pml4e, pp1, 0x0, 0) < 0);

	// free pp0 and try again: pp0 should be used for page table
	page_free(pp0);
	assert(page_insert(boot_pml4e, pp1, 0x0, 0) < 0);
	page_free(pp2);
	page_free(pp3);
	assert(page_insert(boot_pml4e, pp1, 0x0, 0) == 0);
	assert((PTE_ADDR(boot_pml4e[0]) == page2pa(pp0) || PTE_ADDR(boot_pml4e[0]) == page2pa(pp2) || PTE_ADDR(boot_pml4e[0]) == page2pa(pp3) ));
	assert(check_va2pa(boot_pml4e, 0x0) == page2pa(pp1));

	assert(pp1->pp_ref == 1);
	assert(pp0->pp_ref == 1);
	assert(pp2->pp_ref == 1);
	//should be able to map pp3 at PGSIZE because pp0 is already allocated for page table
	assert(page_insert(boot_pml4e, pp3, (void*) PGSIZE, 0) == 0);
	assert(check_va2pa(boot_pml4e, PGSIZE) == page2pa(pp3));
	assert(pp3->pp_ref == 2);

	// should be no free memory
	assert(!page_alloc(0));

	// should be able to map pp3 at PGSIZE because it's already there
	assert(page_insert(boot_pml4e, pp3, (void*) PGSIZE, 0) == 0);
	assert(check_va2pa(boot_pml4e, PGSIZE) == page2pa(pp3));
	assert(pp3->pp_ref == 2);

	// pp3 should NOT be on the free list
	// could happen in ref counts are handled sloppily in page_insert
	assert(!page_alloc(0));
	// check that pgdir_walk returns a pointer to the pte
	pdpe = KADDR(PTE_ADDR(boot_pml4e[PML4(PGSIZE)]));
	pde = KADDR(PTE_ADDR(pdpe[PDPE(PGSIZE)]));
	ptep = KADDR(PTE_ADDR(pde[PDX(PGSIZE)]));


	//cprintf(" *****************Test PTE [] ***************:%x\n",PTE_ADDR(pte[PTX(va)]);


	assert(pml4e_walk(boot_pml4e, (void*)PGSIZE, 0) == ptep+PTX(PGSIZE));

	// should be able to change permissions too.
	assert(page_insert(boot_pml4e, pp3, (void*) PGSIZE, PTE_U) == 0);
	assert(check_va2pa(boot_pml4e, PGSIZE) == page2pa(pp3));
	assert(pp3->pp_ref == 2);
	assert(*pml4e_walk(boot_pml4e, (void*) PGSIZE, 0) & PTE_U);
	assert(boot_pml4e[0] & PTE_U);


	// should not be able to map at PTSIZE because need free page for page table
	assert(page_insert(boot_pml4e, pp0, (void*) PTSIZE, 0) < 0);

	//page_insert(boot_pml4e, pp1, (void*) PGSIZE, 0);
	// insert pp1 at PGSIZE (replacing pp3)
	assert(page_insert(boot_pml4e, pp1, (void*) PGSIZE, 0) == 0);
	assert(!(*pml4e_walk(boot_pml4e, (void*) PGSIZE, 0) & PTE_U));

	// should have pp1 at both 0 and PGSIZE
	assert(check_va2pa(boot_pml4e, 0) == page2pa(pp1));
	assert(check_va2pa(boot_pml4e, PGSIZE) == page2pa(pp1));
	// ... and ref counts should reflect this
	assert(pp1->pp_ref == 2);
	assert(pp3->pp_ref == 1);
	// unmapping pp1 at 0 should keep pp1 at PGSIZE
	page_remove(boot_pml4e, 0x0);
	assert(check_va2pa(boot_pml4e, 0x0) == ~0);
	assert(check_va2pa(boot_pml4e, PGSIZE) == page2pa(pp1));
	assert(pp1->pp_ref == 1);
	assert(pp3->pp_ref == 1);

	// Test re-inserting pp1 at PGSIZE.
	// Thanks to Varun Agrawal for suggesting this test case.
	assert(page_insert(boot_pml4e, pp1, (void*) PGSIZE, 0) == 0);
	assert(pp1->pp_ref);
	assert(pp1->pp_link == NULL);

	// unmapping pp1 at PGSIZE should free it
	page_remove(boot_pml4e, (void*) PGSIZE);
	assert(check_va2pa(boot_pml4e, 0x0) == ~0);
	assert(check_va2pa(boot_pml4e, PGSIZE) == ~0);
	assert(pp1->pp_ref == 0);
	assert(pp3->pp_ref == 1);


#if 0
	// should be able to page_insert to change a page
	// and see the new data immediately.
	memset(page2kva(pp1), 1, PGSIZE);
	memset(page2kva(pp2), 2, PGSIZE);
	page_insert(boot_pgdir, pp1, 0x0, 0);
	assert(pp1->pp_ref == 1);
	assert(*(int*)0 == 0x01010101);
	page_insert(boot_pgdir, pp2, 0x0, 0);
	assert(*(int*)0 == 0x02020202);
	assert(pp2->pp_ref == 1);
	assert(pp1->pp_ref == 0);
	page_remove(boot_pgdir, 0x0);
	assert(pp2->pp_ref == 0);
#endif

	// forcibly take pp3 back
	assert(PTE_ADDR(boot_pml4e[0]) == page2pa(pp3));
	boot_pml4e[0] = 0;
	assert(pp3->pp_ref == 1);
	page_decref(pp3);
	// check pointer arithmetic in pml4e_walk
	page_decref(pp0);
	page_decref(pp2);
	va = (void*)(PGSIZE * 100);
	ptep = pml4e_walk(boot_pml4e, va, 1);
	pdpe = KADDR(PTE_ADDR(boot_pml4e[PML4(va)]));
	pde  = KADDR(PTE_ADDR(pdpe[PDPE(va)]));
	ptep1 = KADDR(PTE_ADDR(pde[PDX(va)]));
	assert(ptep == ptep1 + PTX(va));

	// check that new page tables get cleared
	page_decref(pp4);
	memset(page2kva(pp4), 0xFF, PGSIZE);
	pml4e_walk(boot_pml4e, 0x0, 1);
	pdpe = KADDR(PTE_ADDR(boot_pml4e[0]));
	pde  = KADDR(PTE_ADDR(pdpe[0]));
	ptep  = KADDR(PTE_ADDR(pde[0]));
	for(i=0; i<NPTENTRIES; i++)
		assert((ptep[i] & PTE_P) == 0);
	boot_pml4e[0] = 0;

	// give free list back
	page_free_list = fl;

	// free the pages we took
	page_decref(pp0);
	page_decref(pp1);
	page_decref(pp2);

	// test mmio_map_region
	mm1 = (uintptr_t) mmio_map_region(0, 4097);
	mm2 = (uintptr_t) mmio_map_region(0, 4096);
	// check that they're in the right region
	assert(mm1 >= MMIOBASE && mm1 + 8096 < MMIOLIM);
	assert(mm2 >= MMIOBASE && mm2 + 8096 < MMIOLIM);
	// check that they're page-aligned
	assert(mm1 % PGSIZE == 0 && mm2 % PGSIZE == 0);
	// check that they don't overlap
	assert(mm1 + 8096 <= mm2);
	// check page mappingsasdfasd

	assert(check_va2pa(boot_pml4e, mm1) == 0);
	assert(check_va2pa(boot_pml4e, mm1+PGSIZE) == PGSIZE);
	assert(check_va2pa(boot_pml4e, mm2) == 0);
	assert(check_va2pa(boot_pml4e, mm2+PGSIZE) == ~0);
	// check permissions
	assert(*pml4e_walk(boot_pml4e, (void*) mm1, 0) & (PTE_W|PTE_PWT|PTE_PCD));
	assert(!(*pml4e_walk(boot_pml4e, (void*) mm1, 0) & PTE_U));
	// clear the mappings
	*pml4e_walk(boot_pml4e, (void*) mm1, 0) = 0;
	*pml4e_walk(boot_pml4e, (void*) mm1 + PGSIZE, 0) = 0;
	*pml4e_walk(boot_pml4e, (void*) mm2, 0) = 0;

	cprintf("check_page() succeeded!\n");
}
